export const HOSPITAL = {
  "id": "병원광고연구소",
  "name": "병원광고연구소",
  "code": "병원",
  "color": "#ec4899",
  "monthlyPublishGoal": 8,
  "seoTitle": "병원광고연구소 블로그",
  "description": "병원 옥외광고를 직접 집행하며 확인한 매체별 단가, 심의 기준, 효과 측정 방법을 기록합니다. 검색만으로는 알기 어려운 판단 기준을 병원광고연구소가 정리해 드립니다.",
  "alternateNames": [],
  "knowsAbout": [],
  "telephone": "",
  "streetAddress": "",
  "addressLocality": "",
  "addressRegion": "",
  "postalCode": "",
  "doctorName": "",
  "doctorTitle": "",
  "logoUrl": "",
  "imageUrl": "",
  "sameAs": [],
  "founder": "",
  "areaServed": [],
  "about": [],
  "cmsUrl": "https://bioaddlabgeo.web.app",
  "siteUrl": "https://www.medicaladlab.com",
  "schemaProfile": "business",
  "firebaseApiKey": "AIzaSyBPa4_gNO-BCG5yGhl3atBBtKkMGroX6nc",
  "firebaseProjectId": "bioaddlabgeo"
} as const;
