export const HOSPITAL = {
  "id": "병원광고연구소",
  "name": "병원광고연구소",
  "code": "병원",
  "color": "#ec4899",
  "monthlyPublishGoal": 8,
  "seoTitle": "병원광고연구소 블로그",
  "description": "",
  "alternateNames": [],
  "knowsAbout": [],
  "telephone": "",
  "streetAddress": "",
  "addressLocality": "",
  "addressRegion": "",
  "postalCode": "",
  "doctorName": "",
  "doctorTitle": "",
  "logoUrl": "",
  "imageUrl": "",
  "sameAs": [],
  "founder": "",
  "areaServed": [],
  "about": [],
  "cmsUrl": "https://bioaddlabgeo.web.app",
  "siteUrl": "",
  "schemaProfile": "business",
  "firebaseApiKey": "AIzaSyBPa4_gNO-BCG5yGhl3atBBtKkMGroX6nc",
  "firebaseProjectId": "bioaddlabgeo"
} as const;
